// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _132ndWebsite.Infrastructure.Data;

#nullable disable

namespace _132ndWebsite.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_132ndWebsite.Core.Models.Squadron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Squadrons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Callsign = "The Panthers",
                            Name = "494th vFighter Squadron"
                        },
                        new
                        {
                            Id = 2,
                            Callsign = "The Peregrines",
                            Name = "388th Fighter Squadron"
                        },
                        new
                        {
                            Id = 3,
                            Callsign = "Ravens",
                            Name = "335th Special Operations Squadron"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
